- type: job
  id: NCRCommander
  setPreference: true
  hideWithoutJobWhitelist: false
  hideIfPlaytimeRequirementsNotMet: false
  jobWhitelistBypassesRoleTimers: true
  overrideConsoleVisibility: false
  canBeAntag: true
  name: job-name-ncr-commander
  description: job-description-ncr-commander
  playTimeTracker: NCRCommander
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement # T7 faction timelock (40h NCR)
      department: NCR
      min: 144000 # 40 hours
  weight: 120
  startingGear: NCRCommanderGear
  icon: "JobIconNcrLeader"
  supervisors: job-supervisors-ncr-commander
  requireAdminNotify: true
  alwaysUseSpawner: true
  access:
  - NCR
  - NCRSGT
  - NCRMedic
  - NCRLT
  - NCRCaptain
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRCommanderGear
  equipment:
    head: N14ClothingHeadHatNCRBeretOfficer
    back: N14ClothingBackpackNCR
    jumpsuit: N14ClothingOfficerUniformNCRDesert
    outerClothing: N14ClothingOuterNCRDressJacketCO
    shoes: N14ClothingBootsCombatFilled

    belt: ClothingBeltNCR
    eyes: ClothingEyesGlassesSunglasses
    ears: N14ClothingHeadsetNCR
    pocket1: NCRcaptainloadoutkits
    pocket2: TrainingManualPowerArmorOperation
    id: N14IDNCRDogtagCaptain
  innerClothingSkirt: N14ClothingOfficerUniformNCRDesert
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage:
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCRCommander
