- type: job
  id: NCRNCO
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: false
  jobWhitelistBypassesRoleTimers: true
  weight: 50
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-ncr-nco
  description: job-description-ncr-nco
  playTimeTracker: NCRSquadLeader
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement # T5 faction timelock (16h NCR)
      department: NCR
      min: 57600 # 16 hours
  startingGear: NCRNCOGear
  icon: "JobIconNcrSerg"
  supervisors: job-supervisors-ncr-nco
  alwaysUseSpawner: true
  access:
  - NCR
  - NCRSGT
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRNCOGear
  equipment:
    back: N14ClothingBackpackNCR
    hands: N14ClothingHandsGlovesCombat
    jumpsuit: N14ClothingOfficerUniformNCRDesert
    shoes: N14ClothingBootsCombatFilled
    ears: N14ClothingHeadsetNCR

    belt: ClothingBeltNCR
    outerClothing: MisfitsNCRHeavyCombatArmor # T5 armor (0.70/0.65)
    pocket1: NCRSGTloadoutkits
    pocket2: RadioHandheld
    id: N14IDNCRDogtagNCO
  innerClothingSkirt: N14ClothingOfficerUniformNCRDesert
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage:
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCRSquadLeader
