- type: job
  id: NCREngineer
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: false
  jobWhitelistBypassesRoleTimers: true
  overrideConsoleVisibility: false
  canBeAntag: false
  weight: 41
  name: job-name-ncr-engineer
  description: job-description-ncr-engineer
  playTimeTracker: NCREngineer
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement # T4 faction timelock (12h NCR)
      department: NCR
      min: 43200 # 12 hours
  startingGear: NCREngineerGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-ncr-nco
  alwaysUseSpawner: true
  access:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCREngineerGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetalDesert # Corvax-Change
    back: N14ClothingBackpackNCR # Corvax-Change
    jumpsuit: N14ClothingUniformNCRDesert # Corvax-Change
    outerClothing: N14ClothingOuterNCRPouchedVestDesert # Forge-Change
    shoes: N14ClothingBootsLeatherFilled
    ears: N14ClothingHeadsetNCR # #Misfits Add - NCR radio earpiece
    hands: N14ClothingHandsGlovesCombat

    id: N14IDNCRDogtagEngineer
    pocket1: NCRengineerloadoutkits
  innerClothingSkirt: N14ClothingUniformNCRDesert # Corvax-Change
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCREngineer
