// #Misfits Refactor - Admin player-war force panel.

using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.Network;

namespace Content.Client._Misfits.FactionWar.UI;

/// <summary>
/// Admin-only Force War window. Selects aggressor + target from all war-capable factions,
/// optional casus belli, and fires the event to the server.
/// Also includes a Force Ceasefire section listing active wars.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ForceWarWindow : FancyWindow
{
    public event Action<NetUserId, string, NetUserId, string, string>? OnForceWar;

    public event Action<NetUserId, NetUserId>? OnForceCeasefire;

    private readonly List<OnlinePlayerInfo> _players = new();

    private readonly List<PlayerWarEntry> _activeWarEntries = new();

    /// <summary>Whether the Force War button is in the "confirm" state (second press fires).</summary>
    private bool _confirmWarPending;

    /// <summary>Whether the Force Ceasefire button is in the "confirm" state.</summary>
    private bool _confirmCeasefirePending;

    public ForceWarWindow()
    {
        RobustXamlLoader.Load(this);

        // Commit dropdown selection and reset confirm states when selection changes.
        AggressorSelector.OnItemSelected += args => { AggressorSelector.SelectId(args.Id); ResetWarConfirm(); };
        TargetSelector.OnItemSelected    += args => { TargetSelector.SelectId(args.Id); ResetWarConfirm(); };
        CeasefireWarSelector.OnItemSelected += args => { CeasefireWarSelector.SelectId(args.Id); ResetCeasefireConfirm(); };

        ForceWarButton.OnPressed += _ => SubmitForceWar();
        ForceCeasefireButton.OnPressed += _ => SubmitForceCeasefire();
    }

    /// <summary>
    /// Update the ceasefire section with the current list of active wars.
    /// Called by FactionWarClientSystem when war state changes.
    /// </summary>
    public void UpdateActiveWars(IReadOnlyList<PlayerWarEntry> activeWars)
    {
        _activeWarEntries.Clear();
        CeasefireWarSelector.Clear();
        ResetCeasefireConfirm();

        // Clear stale result labels when war state changes.
        ResultLabel.SetMarkup(string.Empty);
        CeasefireResultLabel.SetMarkup(string.Empty);

        foreach (var war in activeWars)
        {
            _activeWarEntries.Add(war);
            var phaseTag = war.Phase == WarPhase.Pending ? "[PENDING] " : "";
            var label = $"{phaseTag}{war.SideName1} vs {war.SideName2}";
            CeasefireWarSelector.AddItem(label);
        }

        ForceCeasefireButton.Disabled = activeWars.Count == 0;
    }

    public void UpdateOnlinePlayers(IReadOnlyList<OnlinePlayerInfo> players)
    {
        _players.Clear();
        _players.AddRange(players.OrderBy(p => p.CharacterName));

        AggressorSelector.Clear();
        TargetSelector.Clear();

        foreach (var player in _players)
        {
            AggressorSelector.AddItem(player.CharacterName);
            TargetSelector.AddItem(player.CharacterName);
        }

        if (_players.Count > 1)
            TargetSelector.SelectId(1);
    }

    /// <summary>Display a success or error message in the declare-war result label.</summary>
    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        ResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    /// <summary>Display a success or error message in the ceasefire result label.</summary>
    public void ShowCeasefireResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        CeasefireResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    private void SubmitForceWar()
    {
        var aggIdx = AggressorSelector.SelectedId;
        var tgtIdx = TargetSelector.SelectedId;

        if (aggIdx < 0 || aggIdx >= _players.Count ||
            tgtIdx < 0 || tgtIdx >= _players.Count)
            return;

        var aggressor = _players[aggIdx];
        var target = _players[tgtIdx];

        if (aggressor.UserId == target.UserId)
        {
            ShowResult(false, "Player 1 and Player 2 cannot be the same.");
            return;
        }

        if (!_confirmWarPending)
        {
            // First press — switch to confirmation state.
            _confirmWarPending = true;
            ForceWarButton.Text = "CONFIRM - Press Again to Force War";
            ForceWarButton.Modulate = Color.OrangeRed;
            ShowResult(false, "Are you sure? Press the button again to force-declare war.");
            return;
        }

        // Second press — confirmed, fire the event.
        var reason = CasusBelliEdit.Text.Trim();
        if (string.IsNullOrEmpty(reason))
            reason = "Admin-forced war (testing)";

        var side1 = string.IsNullOrWhiteSpace(aggressor.CharacterName) ? "Side 1" : $"{aggressor.CharacterName}'s Side";
        var side2 = string.IsNullOrWhiteSpace(target.CharacterName) ? "Side 2" : $"{target.CharacterName}'s Side";

        OnForceWar?.Invoke(aggressor.UserId, side1, target.UserId, side2, reason);
        ResetWarConfirm();
    }

    private void SubmitForceCeasefire()
    {
        var idx = CeasefireWarSelector.SelectedId;
        if (idx < 0 || idx >= _activeWarEntries.Count)
            return;

        if (!_confirmCeasefirePending)
        {
            // First press — switch to confirmation state.
            _confirmCeasefirePending = true;
            ForceCeasefireButton.Text = "CONFIRM - Press Again to Force Ceasefire";
            ForceCeasefireButton.Modulate = Color.OrangeRed;
            ShowCeasefireResult(false, "Are you sure? Press the button again to force-end this war.");
            return;
        }

        // Second press — confirmed, fire the event.
        var war = _activeWarEntries[idx];
        OnForceCeasefire?.Invoke(war.DeclaredByPlayer, war.DeclaredAgainstPlayer);
        ResetCeasefireConfirm();
    }

    private void ResetWarConfirm()
    {
        _confirmWarPending = false;
        ForceWarButton.Text = "Force War";
        ForceWarButton.Modulate = Color.White;
    }

    private void ResetCeasefireConfirm()
    {
        _confirmCeasefirePending = false;
        ForceCeasefireButton.Text = "Force Ceasefire";
        ForceCeasefireButton.Modulate = Color.White;
    }
}
