// #Misfits Refactor - Player-war join panel.
// Allows players to join a pending player-vs-player war on side 1 or 2.

using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.Network;

namespace Content.Client._Misfits.FactionWar.UI;

[GenerateTypedNameReferences]
public sealed partial class WarJoinWindow : FancyWindow
{
    public event Action<NetUserId, NetUserId, byte>? OnJoinWar;

    private readonly List<PlayerWarEntry> _pendingWars = new();
    private readonly List<(string Display, byte Side)> _sideItems = new();
    private bool _confirmPending;

    public WarJoinWindow()
    {
        RobustXamlLoader.Load(this);

        // KOS warning — hardcoded markup (FTL can't have lines starting with '[').
        WarningLabel.SetMarkup(
            "[color=#FF4500][bold]WARNING[/bold][/color]\n" +
            "By joining this war you become [bold]Kill-On-Sight (KOS)[/bold] to the opposing faction.\n" +
            "Enemy combatants may kill you without negotiation or warning.\n" +
            "This cannot be undone until the war ends.");

        JoinButton.OnPressed += _ => OnJoinPressed();
        WarSelector.OnItemSelected += OnWarSelected;
        SideSelector.OnItemSelected += args => { SideSelector.SelectId(args.Id); ResetConfirm(); };

        FactionWideCheck.Visible = false;
        FactionWideHint.Visible = false;
    }

    /// <summary>
    /// Update the panel with current pending-war data from the server.
    /// </summary>
    public void UpdateState(
        PlayerWarJoinPanelDataEvent data)
    {
        _pendingWars.Clear();
        _pendingWars.AddRange(data.AvailableWars);

        WarSelector.Clear();
        SideSelector.Clear();
        _sideItems.Clear();
        ResetConfirm();
        FactionWideCheck.Visible = false;
        FactionWideHint.Visible = false;
        BlockReasonLabel.Visible = false;

        if (data.AlreadyInWar)
        {
            ShowResult(false, "You have already joined a war.");
            JoinButton.Disabled = true;
            return;
        }

        if (_pendingWars.Count == 0)
        {
            ShowResult(false, data.StatusMessage ?? Loc.GetString("faction-war-join-no-pending"));
            JoinButton.Disabled = true;
            return;
        }

        JoinButton.Disabled = false;

        for (var i = 0; i < _pendingWars.Count; i++)
        {
            var w = _pendingWars[i];
            var label = $"{w.SideName1} vs {w.SideName2}";
            WarSelector.AddItem(label);
        }

        // Auto-select first war and populate sides.
        if (_pendingWars.Count > 0)
        {
            WarSelector.SelectId(0);
            PopulateSides(0);
        }

        ClearResult();
    }

    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        JoinResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    // ── Private ────────────────────────────────────────────────────────────

    private void OnWarSelected(OptionButton.ItemSelectedEventArgs args)
    {
        WarSelector.SelectId(args.Id);
        PopulateSides(args.Id);
        ResetConfirm();
    }

    private void PopulateSides(int warIndex)
    {
        SideSelector.Clear();
        _sideItems.Clear();

        if (warIndex < 0 || warIndex >= _pendingWars.Count)
            return;

        var war = _pendingWars[warIndex];

        _sideItems.Add(($"{war.SideName1}", 1));
        _sideItems.Add(($"{war.SideName2}", 2));

        SideSelector.AddItem(_sideItems[0].Display);
        SideSelector.AddItem(_sideItems[1].Display);
        SideSelector.SelectId(0);
    }

    private void OnJoinPressed()
    {
        if (WarSelector.ItemCount == 0 || SideSelector.ItemCount == 0)
            return;

        var warIdx = WarSelector.SelectedId;
        if (warIdx < 0 || warIdx >= _pendingWars.Count)
            return;

        var sideIdx = SideSelector.SelectedId;
        if (sideIdx < 0 || sideIdx >= _sideItems.Count)
            return;

        if (!_confirmPending)
        {
            _confirmPending = true;
            JoinButton.Text = Loc.GetString("faction-war-join-confirm-button");
            JoinButton.Modulate = Color.OrangeRed;
            ShowResult(false, Loc.GetString("faction-war-join-kos-confirm"));
            return;
        }

        var war = _pendingWars[warIdx];
        var chosenSide = _sideItems[sideIdx].Side;
        OnJoinWar?.Invoke(war.DeclaredByPlayer, war.DeclaredAgainstPlayer, chosenSide);
        ResetConfirm();
    }

    private void ResetConfirm()
    {
        _confirmPending = false;
        JoinButton.Text = Loc.GetString("faction-war-join-button");
        JoinButton.Modulate = Color.White;
    }

    private void ClearResult()
    {
        JoinResultLabel.SetMarkup(string.Empty);
    }
}
